# Generated by Django 5.1.6 on 2025-02-28 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('growth_rate', models.FloatField()),
                ('profitability', models.FloatField()),
                ('cash_flow', models.DecimalField(decimal_places=2, max_digits=15)),
                ('team_size', models.IntegerField()),
                ('founder_experience', models.IntegerField(help_text='Years of experience')),
                ('market_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('competition_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('investment_history', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
    ]
